### ISSUE TITLE
再谈代理

### ISSUE THREAD

**Issue by cutepig123** [cutepig123/gitblog#46]
再谈代理

上次写过一个blog https://github.com/cutepig123/gitblog/issues/24 当时的要求已经基本达到。主要是实现一个端口提供多个服务，我基于一个开源代理修改而来，具体代码见https://github.com/cutepig123/dumb_proxy

现在又想继续增强实现如下功能

- 支持数据加密
- 支持不能用代理的软件通过代理

一个例子如下

vnc客户端 -> http proxy -> dumb proxy 1 ->加密的数据经过internet ->dumb proxy 2 ->vnc服务端

vnc客户端

```
连接 localhost:15900
```

dumb proxy 1设置如下

```toml
[tcppm.a]
port = 15900
target = "127.0.0.1:8080"
need_xor = true

[http_proxy_client.a]
port = 8080
http_proxy_server = "10.1.1.101:8080"
target = "dumb proxy 2:80"
```

dumb proxy 2设置如下

```toml
[tcppm.a]
port = 80
target = "127.0.0.1:5900"
need_xor = true
```

分析

客户端: 链接15900 -》转发到8080-》经过http proxy转发到proxy2:80 --> 转发到服务端5900

代码实现

- `F:\_codes\dumb_proxy` --> https://github.com/cutepig123/dumb_proxy

- `F:\_codes\Detours\samples\tracetcp-sockscap`稍后上传代码
